/* 
 * File:   errorno.hpp
 * Author: jjdengjj
 */

#ifndef _ERRORNO_HPP
#define	_ERRORNO_HPP

//MainServer Error NO
#define _ERRORNO_MAINSERVER_SUCCESS 0
#define _ERRORNO_MAINSERVER_SOCKETFDCREATE 1
#define _ERRORNO_MAINSERVER_SOCKETFDNONBLOCK 2
#define _ERRORNO_MAINSERVER_SOCKETBIND 3
#define _ERRORNO_MAINSERVER_SOCKETLISTEN 4
#define _ERRORNO_MAINSERVER_SERVERLISTENTHREADCREATE 5
#define _ERRORNO_MAINSERVER_SERVERACCEPTCLIENT 6
#define _ERRORNO_MAINSERVER_CANCELACCEPTTHREAD 7

//MainClient Error NO
#define _ERRORNO_MAINCLIENT_SUCCESS 0
#define _ERRORNO_MAINCLIENT_RECEIVETHREADCREATE 1
#define _ERRORNO_MAINCLIENT_SENDTHREADCREATE 2
#define _ERRORNO_MAINCLIENT_SOCKETFDNONBLOCK 3
#define _ERRORNO_MAINCLIENT_OUTOFCAPACITY 4
#define _ERRORNO_MAINCLIENT_THREADMUTEXLOCK 5
#define _ERRORNO_MAINCLIENT_THREADMUTEXUNLOCK 6
#define _ERRORNO_MAINCLEINT_NOSUCHCLIENT 7
#define _ERRORNO_MAINCLIENT_CANCELRECEIVETHREAD 8
#define _ERRORNO_MAINCLIENT_CANCELSENDTHREAD 9

#endif	/* _ERRORNO_HPP */
